nodeLinker: hoisted
allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
supportedArchitectures:
  os:
    - current
    - darwin
    - linux
  cpu:
    - current
    - arm64
    - x64
  libc:
    - current
    - glibc
    - musl
